mqttId=USER_MANAGER
maxMessagesInQueue=1000

num_subscriptions=2
subscription_1_topic=user/info
subscription_1_URL_factory=${MQTT_BROKER_URL}
subscription_1_user=${MQTT_USER}
subscription_1_password=${MQTT_PASSWORD}
subscription_1_timeTryReconnect=2
subscription_1_messages=LoginRequest,RegisterRequest,UserInfoRequest

subscription_2_topic=user/password
subscription_2_URL_factory=${MQTT_BROKER_URL}
subscription_2_user=${MQTT_USER}
subscription_2_password=${MQTT_PASSWORD}
subscription_2_timeTryReconnect=2
subscription_2_messages=ChangePasswordEmail,ChangePassword,ChangePasswordSendEmail

num_publications=2
publication_1_topic=user/info
publication_1_URL_factory=${MQTT_BROKER_URL}
publication_1_user=${MQTT_USER}
publication_1_password=${MQTT_PASSWORD}
publication_1_timeTryReconnect=2
publication_1_messages=LoginResponse,RegisterResponse,UserInfo

publication_2_topic=user/password
publication_2_URL_factory=${MQTT_BROKER_URL}
publication_2_user=${MQTT_USER}
publication_2_password=${MQTT_PASSWORD}
publication_2_timeTryReconnect=2
publication_2_messages=ChangePasswordEmailResponse,ChangePasswordResponse

