mqttId=GAME_SERVICE
maxMessagesInQueue=3

num_subscriptions=1
subscription_1_topic=game/info
subscription_1_URL_factory=${MQTT_BROKER_URL}
subscription_1_user=${MQTT_USER}
subscription_1_password=${MQTT_PASSWORD}
subscription_1_timeTryReconnect=2
subscription_1_messages=GamesRequest,SaveGame

num_publications=1
publication_1_topic=game/info
publication_1_URL_factory=${MQTT_BROKER_URL}
publication_1_user=${MQTT_USER}
publication_1_password=${MQTT_PASSWORD}
publication_1_timeTryReconnect=2
publication_1_messages=Games,SaveGameResponse

