package com.chessfraud.gateway.auth.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Component;

import java.time.Duration;

/**
 * Redis-backed store for password-reset codes issued by /auth/forgot-password. Redis' own TTL
 * replaces the previous per-pod ConcurrentHashMap + scheduled sweep: it expires codes on its own
 * and, unlike a local map, is visible to every gateway replica - a code generated by one pod is
 * validated correctly regardless of which pod handles /auth/reset-password.
 */
@Component
public class PasswordResetCodeStore {
    private static final Logger log = LoggerFactory.getLogger(PasswordResetCodeStore.class);
    private static final String KEY_PREFIX = "reset-code:";
    private static final Duration TTL = Duration.ofSeconds(600);

    private final StringRedisTemplate redis;

    public PasswordResetCodeStore(StringRedisTemplate redis) {
        this.redis = redis;
    }

    public void store(String email, String code) {
        if (email == null || email.isBlank() || code == null || code.isBlank()) {
            return;
        }
        redis.opsForValue().set(KEY_PREFIX + email.toLowerCase(), code, TTL);
        log.info("[AUTH] Reset code stored for email '{}', expires in {}s", email, TTL.getSeconds());
    }

    /** Validates the code for the given email and consumes it (valid or not). */
    public boolean validateAndConsume(String email, String code) {
        String stored = redis.opsForValue().getAndDelete(KEY_PREFIX + email.toLowerCase());
        return stored != null && stored.equals(code);
    }
}
