mqttId=GATEWAY
maxMessagesInQueue=3

num_subscriptions=4
subscription_1_topic=user/info
subscription_1_URL_factory=${MQTT_BROKER_URL}
subscription_1_user=${MQTT_USER}
subscription_1_password=${MQTT_PASSWORD}
subscription_1_timeTryReconnect=2
subscription_1_messages=LoginResponse,RegisterResponse,UserInfo

subscription_2_topic=user/password
subscription_2_URL_factory=${MQTT_BROKER_URL}
subscription_2_user=${MQTT_USER}
subscription_2_password=${MQTT_PASSWORD}
subscription_2_timeTryReconnect=2
subscription_2_messages=ChangePasswordEmailResponse,ChangePasswordResponse

subscription_3_topic=game/info
subscription_3_URL_factory=${MQTT_BROKER_URL}
subscription_3_user=${MQTT_USER}
subscription_3_password=${MQTT_PASSWORD}
subscription_3_timeTryReconnect=2
subscription_3_messages=Games,SaveGameResponse

subscription_4_topic=game/analyze
subscription_4_URL_factory=${MQTT_BROKER_URL}
subscription_4_user=${MQTT_USER}
subscription_4_password=${MQTT_PASSWORD}
subscription_4_timeTryReconnect=2
subscription_4_messages=AnalyzeGameResponse

num_publications=4
publication_1_topic=user/info
publication_1_URL_factory=${MQTT_BROKER_URL}
publication_1_user=${MQTT_USER}
publication_1_password=${MQTT_PASSWORD}
publication_1_timeTryReconnect=2
publication_1_messages=LoginRequest,RegisterRequest,UserInfoRequest

publication_2_topic=user/password
publication_2_URL_factory=${MQTT_BROKER_URL}
publication_2_user=${MQTT_USER}
publication_2_password=${MQTT_PASSWORD}
publication_2_timeTryReconnect=2
publication_2_messages=ChangePasswordEmail,ChangePassword,ChangePasswordSendEmail

publication_3_topic=game/info
publication_3_URL_factory=${MQTT_BROKER_URL}
publication_3_user=${MQTT_USER}
publication_3_password=${MQTT_PASSWORD}
publication_3_timeTryReconnect=2
publication_3_messages=GamesRequest,SaveGame

publication_4_topic=game/analyze
publication_4_URL_factory=${MQTT_BROKER_URL}
publication_4_user=${MQTT_USER}
publication_4_password=${MQTT_PASSWORD}
publication_4_timeTryReconnect=2
publication_4_messages=AnalyzeGame

