CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    total_games INT NOT NULL DEFAULT 0,
    cheated_games INT NOT NULL DEFAULT 0,
    fair_games INT NOT NULL DEFAULT 0);